### ISSUE TITLE
Why OLAF use 16KHz and 32bit float values?

### ISSUE THREAD

**Issue by konstantin-sancom** [JorenSix/Olaf#9]
Hi!

As I can see, thre is only one thing `ffmpeg` do - converting audio data to 32float 16KHz mono stream.

Why this format of audio data was choosen?

**Comment by JorenSix** [comment]
Hi, the format was chosen for pragmatical reasons. I wanted to avoid fixed point math (16bitle e.g) since I myself find working with values between -1.0f and 1.0f more clear. FFT code is also compatible with 32bit float values on all possible systems (pc's, embedded processors, web audio). It is also straightforward to create and inspect raw audio test files.

The 16kHz sample rate is a tradeoff: using a 512 sample FFT with some overlap gives a favorable FFT block size for fingerprint construction and matching.  It also keeps the computational load lower than working with higher sampling rates.
